### ISSUE TITLE
换行符问题

### ISSUE THREAD

**Issue by zchrissirhcz** [myhub/uc#3]
你好，我看了uc模块python源码，譬如

`/home/zz/soft/miniconda3/lib/python3.7/site-packages/uc/mesh.py`

![image](https://user-images.githubusercontent.com/3831847/85935072-d613ca00-b91e-11ea-99b9-e7af639e25f1.png)

显示为dos，而我目前处于linux环境。说明此文件是：多行文本，行与行之间用CR LF分隔。最后一行末尾有CR LF。或：Windows下编辑，最后有空行。

**Comment by myhub** [comment]
嗯，这个项目以前是在Windows下开发的，所以是CR LF
若有必要的话我后面统一改成LF

**Comment by zchrissirhcz** [comment]
读取所有代码行然后rstrip再追加"\n"即可，python库会自动根据操作系统把“\n"转为当前系统下的换行符。

实际上我先前写过一个工具，https://github.com/zchrissirhcz/smart_code_copier ，批量操作的时候可以参考

**Comment by myhub** [comment]
ok的，你那边测试下来性能感觉如何？
